Call self.update_property(self._cmode_property) only when the table is Chinese
If self.update_property(self._cmode_property) is called for tables
which are not Chinese, like translit.txt (LANGUAGES = ru_RU)
or ipa-x-sampa.txt (LANGUAGES=other), these input methods don’t work
because then there is no _cmode_property. Fails then with the error:

fail to create engine ipa-x-sampa
Traceback (most recent call last):
  File "/usr/share/ibus-table/engine/factory.py", line 90, in do_create_engine
    + str(self.engine_id), self.dbdict[name])
  File "/usr/share/ibus-table/engine/table.py", line 1165, in __init__

  File "/usr/share/ibus-table/engine/table.py", line 1173, in reset
    self._update_ui ()
  File "/usr/share/ibus-table/engine/table.py", line 1235, in _init_properties

  File "/usr/share/ibus-table/engine/table.py", line 1291, in _refresh_properties

AttributeError: 'tabengine' object has no attribute '_cmode_property'
Traceback (most recent call last):
  File "/usr/share/ibus-table/engine/factory.py", line 98, in do_create_engine
    raise Exception("Can not create engine %s" % engine_name)
Exception: Can not create engine ipa-x-sampa

I caused this problem when porting to GObjectIntrospection.